name: Build C file on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Build C file
        run: |
          ls
          pwd
          gcc -o project.exe project.c
