name: Build C file on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Build C file
        run: |
          gcc -o D:\a\build-c\build-c\project.exe D:\a\build-c\build-c\project.c
