name: Build C file on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64

      - name: Build C file
        run: |
          choco install mingw -y
          gcc -o project.exe project.c
